### PR TITLE
Script for send batch emails added

### PR DESCRIPTION
**Pull request by Ronak-Jethava**
Scripts for **send batch emails** is added in new folder _Send Batch Emails_. 

Solves #5  

- [x] Created scripts for **send batch emails**. 
- [x] Added README.md in folder for guidelines to use the script.

### CODE REVIEW

**Comment by DevChoganwala** [comment]
Great work with the scripts @Ronak-Jethava , could you please make the following changes:
1. Rename the folder to 'send_batch_emails'.
2. Add a `requirements.txt` containing packages required to run the script

Thanks.

**Comment by Ronak-Jethava** [comment]
@DevChoganwala I did the above two required changes.

**Comment by DevChoganwala** [comment]
Hey @Ronak-Jethava , `requirements.txt` does not need to be manually written, it needs to be generated using pip so that script users can directly install packages required using pip.

If you're not working on a virtual environment, make a new virtual environment (in the folder of script) using:

1. `pip install virtualenv`
2. `virtualenv -p <path_to_python> <name_of_env>` (This will create a folder with name <name_of_env>, make sure to exclude that when committing)
3. `source <name_of_env>/bin/activate`
4. Install all the packages required for the script using `pip install <package_name>`

To generate `requirements.txt` :
5. `pip freeze --local > requirements.txt`

This will save a requirements.txt file in your folder. Please make sure to also exclude virtual environment folder when committing.

Thanks!

**Comment by DevChoganwala** [comment]
LGTM! Thanks :)

**Pull request merged**
